-- ─────────────────────────────────────────────────────────────
-- TEST ONLY — volunteer_integration_test_bootstrap.sql
--
-- Purpose: prerequisites for a FRESH ISOLATED test database so that
-- Phase 6A Scenario A (server/__tests__/loveActivism.integration.
-- happyPath.test.js) can run WITHOUT touching production.
--
-- NEVER run this against production / live Supabase.
-- Contains NO credentials and NO production data.
-- Does NOT alter production migrations 001–016.
-- Does NOT change application code.
-- Does NOT add RLS (not required by 015/016 or Scenario A).
-- Does NOT invent Volunteer business rules.
--
-- What this file creates (prerequisites ONLY):
--   1. pgcrypto extension          (gen_random_uuid() used by 015)
--   2. public.schema_migrations    (015/016 INSERT into it)
--   3. minimal public.users        (015 FK: love_activism_events.
--                                   created_by INTEGER REFERENCES
--                                   public.users(id); Scenario A
--                                   checks SELECT id FROM public.users
--                                   WHERE id = $1)
--   4. minimal public.audit_log    (loveActivismEvent.service +
--                                   eventBooking.service call
--                                   logAudit(client, ...) inside the
--                                   same transaction; without this
--                                   table createEvent/booking fails)
--   5. ONE seeded manager user, id = 1 (see below)
--
-- What this file does NOT create:
--   love_activism_events, event_spaces, event_timeslots,
--   volunteer_bookings, attendance, vms_sync.
--   Those come from the real production migrations 015 + 016,
--   applied AFTER this file (see application order below).
-- ─────────────────────────────────────────────────────────────

BEGIN;

-- 1. UUID generation used by 015 table defaults.
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. Migration bookkeeping table expected by 015/016 tail inserts:
--      INSERT INTO public.schema_migrations (id, applied_at, notes) ...
CREATE TABLE IF NOT EXISTS public.schema_migrations (
    id         TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes      TEXT
);

-- 3. Minimal users table — shape derived ONLY from what Scenario A
--    and its call chain actually touch:
--    - 015 FK requires public.users(id) of INTEGER type
--      (created_by INTEGER NOT NULL REFERENCES public.users(id)).
--    - Scenario A beforeAll requires SELECT id FROM public.users
--      WHERE id = $1 to find VOLUNTEER_TEST_USER_ID.
--    - Auth for Scenario A is a pre-signed JWT (role 'manager');
--      no login-table lookup runs, so password_hash/role values here
--      are inert fixtures, not business rules. No role CHECK is added
--      on purpose (do not invent Volunteer business rules).
CREATE TABLE IF NOT EXISTS public.users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    first_name    TEXT,
    last_name     TEXT,
    role          TEXT NOT NULL DEFAULT 'manager',
    password_hash TEXT NOT NULL DEFAULT 'TEST-ONLY-NOT-A-REAL-HASH',
    is_active     BOOLEAN NOT NULL DEFAULT TRUE
);

-- 4. Minimal audit_log — columns derived ONLY from
--    server/src/repositories/auditLog.repository.js:
--      INSERT INTO audit_log
--        (entity_type, entity_id, action, actor_id, reason,
--         approved_by, before_data, after_data)
--    entity_id carries love_activism_events.event_id (UUID), so it is
--    UUID here. actor_id carries Number(actor.id) matching
--    public.users(id) INTEGER. No FKs added (trail must not block
--    fixture cleanup ordering).
--    DROP first so a re-run picks up schema fixes (e.g. entity_id
--    INTEGER→UUID) on an already-provisioned test DB.
DROP TABLE IF EXISTS public.audit_log;
CREATE TABLE public.audit_log (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entity_type TEXT NOT NULL,
    entity_id   UUID NOT NULL,
    action      TEXT NOT NULL,
    actor_id    INTEGER NULL,
    reason      TEXT NULL,
    approved_by INTEGER NULL,
    before_data JSONB NULL,
    after_data  JSONB NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Seeded manager user for Scenario A.
--    SEEDED public.users.id = 1
--    Set VOLUNTEER_TEST_USER_ID=1 afterwards.
--    username matches the JWT username used in the test ('happy.path').
--    password_hash is a dummy marker, never used (auth is JWT-only).
INSERT INTO public.users
    (id, username, first_name, last_name, role, password_hash, is_active)
VALUES
    (1, 'happy.path', 'Happy', 'Path', 'manager', 'TEST-ONLY-NOT-A-REAL-HASH', TRUE)
ON CONFLICT (id) DO NOTHING;

-- Keep the identity sequence past the seeded id so later inserts
-- without explicit ids do not collide with id = 1.
SELECT setval(
    pg_get_serial_sequence('public.users', 'id'),
    GREATEST(1, (SELECT COALESCE(MAX(id), 1) FROM public.users)),
    true
);

COMMIT;

-- ─────────────────────────────────────────────────────────────
-- APPLICATION ORDER for a fresh isolated test DB (psql):
--
--   1. server/database/test/volunteer_integration_test_bootstrap.sql
--        (this file — prerequisites + seed user id 1)
--   2. server/database/migrations/015_create_volunteer_management_tables.sql
--        (creates love_activism_events, event_spaces,
--         event_timeslots, volunteer_bookings, attendance, vms_sync)
--   3. server/database/migrations/016_expand_vms_sync_entity_type.sql
--        (allows vms_sync.entity_type = 'event_booking')
--
-- Example (isolated TEST db only — never production):
--   psql "$VOLUNTEER_TEST_DATABASE_URL" -f server/database/test/volunteer_integration_test_bootstrap.sql
--   psql "$VOLUNTEER_TEST_DATABASE_URL" -f server/database/migrations/015_create_volunteer_management_tables.sql
--   psql "$VOLUNTEER_TEST_DATABASE_URL" -f server/database/migrations/016_expand_vms_sync_entity_type.sql
-- ─────────────────────────────────────────────────────────────
