export const GOAL_TYPES = ['TARGET', 'DIRECTIONAL'];
export const DIRECTIONS = ['INCREASE', 'DECREASE', 'MAINTAIN'];
export const COMPARISON_TYPES = ['TARGET', 'PREVIOUS_PERIOD'];

export const OPERATIONAL_GOAL_METRICS = [
  { id: 'ecd_new_registrations', label: 'New ECD registrations', domain: 'Nourish Our Children', description: 'Number of ECD centres registered during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['cohort', 'status'] },
  { id: 'ecd_active_centres', label: 'Active ECD centres', domain: 'Nourish Our Children', description: 'Number of ECD centres currently active.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['cohort'] },
  { id: 'ecd_children_supported', label: 'Children supported', domain: 'Nourish Our Children', description: 'Number of children supported by active ECD centres.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['cohort', 'status'] },
  { id: 'ecd_collection_compliance', label: 'ECD collection compliance', domain: 'Nourish Our Children', description: 'Percentage of expected ECD collections completed during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['cohort'] },
  { id: 'ecd_non_collections', label: 'ECD non-collections', domain: 'Nourish Our Children', description: 'Number of expected ECD collections not completed during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['DECREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['cohort'] },
  { id: 'ecd_repeat_non_collections', label: 'Repeat ECD non-collections', domain: 'Nourish Our Children', description: 'Number of ECD centres with repeated missed collections during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['DECREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['cohort'] },
  { id: 'ecd_late_collections', label: 'Late ECD collections', domain: 'Nourish Our Children', description: 'Number of ECD collections completed late during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['DECREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['cohort'] },
  { id: 'dispatch_volume', label: 'Dispatch volume', domain: 'Warehouse', description: 'Total number of dispatches completed during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['warehouse', 'dispatchType'] },
  { id: 'dispatch_shortages', label: 'Dispatch shortages', domain: 'Warehouse', description: 'Number of dispatches with shortages during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['DECREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['warehouse', 'product'] },
  { id: 'stock_variance', label: 'Stock variance', domain: 'Warehouse', description: 'Recorded difference between expected and actual stock levels.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['DECREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['warehouse', 'product'] },
  { id: 'low_stock_items', label: 'Low stock items', domain: 'Warehouse', description: 'Number of inventory items below their low stock threshold.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['DECREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['warehouse', 'category'] },
  { id: 'decanting_wastage', label: 'Decanting wastage', domain: 'Warehouse', description: 'Total wastage recorded during decanting in the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['DECREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['product'] },
  { id: 'supplier_lead_time', label: 'Supplier lead time', domain: 'Warehouse', description: 'Average time between procurement order and receipt.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['DECREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['supplier', 'product'] },
  { id: 'volunteer_bookings', label: 'Volunteer bookings', domain: 'Love Activism', description: 'Number of volunteer bookings made during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['eventType', 'eventId'] },
  { id: 'volunteer_attendance', label: 'Volunteer attendance', domain: 'Love Activism', description: 'Number of attended volunteer bookings during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['eventType', 'eventId'] },
  { id: 'volunteer_hours', label: 'Volunteer hours', domain: 'Love Activism', description: 'Total volunteer hours recorded during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['eventType', 'eventId'] },
  { id: 'volunteer_capacity_utilisation', label: 'Volunteer capacity utilisation', domain: 'Love Activism', description: 'Percentage of available volunteer capacity booked or attended.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['eventType', 'eventId'] },
  { id: 'volunteer_no_shows', label: 'Volunteer no-shows', domain: 'Love Activism', description: 'Number of booked volunteers who did not attend during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['DECREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['eventType', 'eventId'] },
  { id: 'compost_kits_issued', label: 'Compost kits issued', domain: 'Feed the Soil', description: 'Number of compost kits issued during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['site', 'recipientType'] },
  { id: 'compost_logged', label: 'Compost logged', domain: 'Feed the Soil', description: 'Number of compost activity logs recorded during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['site'] },
  { id: 'compost_dispatched', label: 'Compost dispatched', domain: 'Feed the Soil', description: 'Number of compost dispatches completed during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['site', 'recipientType'] },
  { id: 'compost_kg_dispatched', label: 'Compost kilograms dispatched', domain: 'Feed the Soil', description: 'Total kilograms of compost dispatched during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['site', 'recipientType'] },
  { id: 'donation_count', label: 'Donation count', domain: 'Donations', description: 'Number of donations recorded during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['donationType', 'donorType'] },
  { id: 'donation_value', label: 'Donation value', domain: 'Donations', description: 'Total value of donations recorded during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['donationType', 'donorType'] },
  { id: 'donations_recognised_as_inventory', label: 'Donations recognised as inventory', domain: 'Donations', description: 'Number of donations recognised into warehouse inventory during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['donationType', 'product'] },
  { id: 'community_requests_fulfilled', label: 'Community requests fulfilled', domain: 'Community', description: 'Number of community requests fulfilled during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['requestType', 'community'] },
  { id: 'community_response_time', label: 'Community response time', domain: 'Community', description: 'Average time taken to respond to community requests.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['DECREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['requestType', 'community'] },
  { id: 'failed_quickbooks_syncs', label: 'Failed QuickBooks syncs', domain: 'Finance', description: 'Number of failed QuickBooks sync attempts during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['DECREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['syncType'] },
  { id: 'finance_handoff_completion', label: 'Finance handoff completion', domain: 'Finance', description: 'Percentage of required finance handoffs completed during the goal period.', supportedGoalTypes: ['TARGET', 'DIRECTIONAL'], supportedDirections: ['INCREASE', 'MAINTAIN'], comparisonType: 'PREVIOUS_PERIOD', supportedFilters: ['handoffType'] },
];


